### PR TITLE
raise_for_status(), and Session for efficient http

### PR DESCRIPTION
**Pull request by kxrob**

### CODE REVIEW

**Comment by terryyin** [comment]
Thanks for the contribution. But where are the tests?

**Comment by kxrob** [comment]
> Thanks for the contribution. But where are the tests?

It doesn't really add new functionality to test. Positive function is already tested by the existing tests.
(Added a test provoking an HTTPError, but not sure if reasonable.)

**Comment by terryyin** [comment]
@kxrob the test looks good to me. Very interesting testing approach. I learned something. Thanks.

There's some duplicate code, do you want to remove them? Eg. extract them together, and/or, pull it up to the caller?

**Comment by kxrob** [comment]
> There's some duplicate code

Is this about the 2 lines for session setup in `_make_request` ?
Its not well equal and interleaved (and Libre has external library); only 2 lines equal on some providers. Pulling session init to `__init__` (super class) would delay imports etc. before real action, and not every provider needs it.  Usage of `requests` library could also change pre provider.
So have no good idea so far how to compress it nice?

I added automatic github CI testing  - upon pull request pushes and upon push to `master` branch (and to a `_ci_test` branch for experiments). The feature would require to be activated in your github repository - in the "Actions" tab of the repo. It ran in my fork (here: https://github.com/kxrob/translate-python/tree/_ci_test )

**Pull request merged**
